---
title: "Lab 8"
author: "Lucy Genua"
date: '2018-03-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load the packages
```{r}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)

```


###Column graph of Texas oil spills
```{r}
oil_spills<-read_csv("oil_spills.csv")

#COOL NOTE: When your column headers have spaces, you can call them with angled apostrophes (symbol under the squiggly, top left of keyboard)

df<-oil_spills %>% 
  filter(`Accident State` =="TX" & `Accident Year`<2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss=sum(`Net Loss (Barrels)`))

colnames(df)<-c("Year", "Loss")

ggplot(df, aes(x=Year, y=Loss))+
  geom_col()
```

###Leaflet plot of spill locations in Texas in 2016
```{r}
df_loc<-oil_spills %>% 
  filter(`Accident State`=="TX" & `Accident Year`==2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc)<-c("latitude", "longitude", "net_loss")


#CONVERT TO SPATIAL DATA FROM LAT/LONG 
oil_sf<-st_as_sf(df_loc, coords=c("longitude", "latitude"), crs=4326)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()

```

